name: Test and coverage

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: cd Deployment && npm install

      - name: Run tests with coverage
        run: cd Deployment && npm run coverage
        # run: cd Deployment && npx nyc mocha

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
          # path-to-lcov: Deployment/coverage/lcov.info

